### ISSUE TITLE
Custom endpoint /macapplications failing due to icon image data in Jamf Pro API response

### ISSUE THREAD

**Issue by et-j** [jamf/SplunkBase#2]
The /macapplications custom endpoint can produce errors relating to XML Length:

`<Error><error>The XML was too long</error><Error>`

This issue appears to stem from the Jamf Pro API's inclusion of icon image data in API responses.

**Comment by PazDak** [comment]
I resolved this with Version 1.0.10 that is currently on Splunk Base.
