### ISSUE TITLE
API Error Request Exception

### ISSUE THREAD

**Issue by mrtc0** [jamf/SplunkBase#3]
The following error is logged in events after installing the app:

```xml
<Error><error>API Error Request Exception</error></Error>
```

**Environments**

* Splunk Cloud
* JAMF-Pro-addon-for-splunk 1.0.10

Inputs settings:

![jamf-pro-splunk-settings](https://user-images.githubusercontent.com/5842353/131948142-e0eddb06-1d80-466c-a8a9-e9283d523f85.png)

We have confirmed that:

- We can be accessed to Jamf server from outside.
- We have granted the privilege of `Computers` (read-only) to user.
- We have set Logging level to `DEBUG`, confirmed app log with SPL`index=_internal source="/opt/splunk/var/log/splunk/jamf_pro_addon_for_splunk_jamf.log"`. Only the following message was logged: `... DEBUG pid = 3988 tid = MainThread file = connectionpool.py: _new_conn: 959 | Starting new HTTPS connection (1): [REDACTED]:8443`

Is there anything we can do to help solve this problem?

**Comment by PazDak** [comment]
Sorry the Logging isn't 100% the best I will make add that to my v2.2.0 as a point of improvement.

The error can only come in one of 2 areas the first is that you get a 400 series on one of the computers when calling it directly or you have a computer ... sometimes called a `ghost record` has issues with the server responding.

Contact the Jamf Support channel they will loop me in to help figure out where exactly this is erroring out.

If haven't please setup prior to the call the Splunk server to use a Service Account only used by Splunk.

**Comment by mrtc0** [comment]
Thank you for your reply.

We have confirmed that there are no 400 series errors and no duplicate computers..., and we contacted Jamf Support.

**Comment by mrtc0** [comment]
I haven't been able to import the data yet, but this seems to be happening only in Splunk Cloud.

- We contacted Jamf Support to investigate, but no ghost records were found.
- Splunk Enterprise was able to import the data successfully

We will contact Splunk Cloud customer support and continue our investigation.

**Comment by PazDak** [comment]
If you respond to the Jamf Ticket that you want help from the developer, I
can get on the ticket and find out what is going on.

Splunk Base is also in the middle of cloud certification for 2.1.N which
will drop your Computer API calls to 1/200th of what they were before.

**Comment by mrtc0** [comment]
We communicated with the Splunk support team and found out that Splunk Cloud restricts external connections to ports other than 80,443/tcp. Our jamf API endpoint was listening at 8443, so it was not connecting. 

I asked Splunk support to allow the instance to connect to port 8443 and successfully imported the event from the Jamf API.

I'm sorry for the confusion. Thank you.
